### ISSUE TITLE
Passenger and Bordkarte require eachother in their respective constructor

### ISSUE THREAD

**Issue by leon16c** [Alexander3a/GSE2#1]
chicken and egg problem?

**Comment by Alexander3a** [comment]
we just set it to null first
https://github.com/Alexander3a/GSE2/blob/867b2ff75704a9dc856a611d9acfe11437af9a0a/src/de/hhn/airline/MainFull.java#LL103C67-L103C67
https://github.com/Alexander3a/GSE2/blob/867b2ff75704a9dc856a611d9acfe11437af9a0a/src/de/hhn/airline/MainFull.java#LL72C46-L72C46
